# Set in environment in case we need to build any extensions
ARG DEFAULT_CUDA_ARCH_LIST="6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0+PTX"

# Builder
FROM nvcr.io/nvidia/tensorrt:24.12-py3 as builder
ARG DEFAULT_CUDA_ARCH_LIST
ENV TORCH_CUDA_ARCH_LIST=${DEFAULT_CUDA_ARCH_LIST}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ninja-build \
        python3-dev \
        python3-pip \
        wget \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

ENV ONEAPI_VERSION=2025.0
RUN wget -q https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB && \
    apt-key add *.PUB && \
    rm *.PUB && \
    echo "deb https://apt.repos.intel.com/oneapi all main" > /etc/apt/sources.list.d/oneAPI.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        intel-oneapi-mkl-devel-$ONEAPI_VERSION \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/root/.cache pip install cmake==3.22.*

ENV ONEDNN_VERSION=3.6.2
RUN wget -q https://github.com/oneapi-src/oneDNN/archive/refs/tags/v${ONEDNN_VERSION}.tar.gz && \
    tar xf *.tar.gz && \
    rm *.tar.gz && \
    cd oneDNN-* && \
    cmake -DCMAKE_BUILD_TYPE=Release -DONEDNN_LIBRARY_TYPE=STATIC -DONEDNN_BUILD_EXAMPLES=OFF -DONEDNN_BUILD_TESTS=OFF -DONEDNN_ENABLE_WORKLOAD=INFERENCE -DONEDNN_ENABLE_PRIMITIVE="CONVOLUTION;REORDER" -DONEDNN_BUILD_GRAPH=OFF . && \
    make -j$(nproc) install && \
    cd .. && \
    rm -r oneDNN-*

WORKDIR /root/CTranslate2

RUN git clone --recursive --branch v3.24.0 https://github.com/OpenNMT/CTranslate2.git .

ARG CXX_FLAGS
ENV CXX_FLAGS=${CXX_FLAGS:-"-msse4.1"}
ARG CUDA_NVCC_FLAGS
ENV CUDA_NVCC_FLAGS=${CUDA_NVCC_FLAGS:-"-Xfatbin=-compress-all"}
ARG DEFAULT_CUDA_ARCH_LIST
ENV CUDA_ARCH_LIST=${DEFAULT_CUDA_ARCH_LIST:-"Common"}
ENV CTRANSLATE2_ROOT=/opt/ctranslate2

RUN mkdir build && \
    cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=${CTRANSLATE2_ROOT} \
          -DWITH_CUDA=ON -DWITH_CUDNN=ON -DWITH_MKL=ON -DWITH_DNNL=ON -DOPENMP_RUNTIME=COMP \
          -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" \
          -DCUDA_NVCC_FLAGS="${CUDA_NVCC_FLAGS}" -DCUDA_ARCH_LIST="${CUDA_ARCH_LIST}" .. && \
    VERBOSE=1 make -j$(nproc) install

ENV LANG=en_US.UTF-8
COPY README.md .

RUN --mount=type=cache,target=/root/.cache cd python && \
    pip --no-cache-dir install -r install_requirements.txt && \
    python3 setup.py bdist_wheel --dist-dir $CTRANSLATE2_ROOT

# Runtime

FROM nvcr.io/nvidia/tensorrt:24.12-py3

WORKDIR /app

# Install zstd and git-lfs for model compression and distribution
RUN apt-get update && apt-get install -y zstd git-lfs && rm -rf /var/lib/apt/lists/*

COPY requirements.txt.24.12 .
# Run pip install with cache so we speedup subsequent rebuild
RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt.24.12

# Install our torch ver matching cuda
RUN --mount=type=cache,target=/root/.cache pip install -U torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1

# Install compiled ctranslate2
ENV CTRANSLATE2_ROOT=/opt/ctranslate2
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CTRANSLATE2_ROOT/lib

COPY --from=builder $CTRANSLATE2_ROOT $CTRANSLATE2_ROOT
RUN python3 -m pip --no-cache-dir install $CTRANSLATE2_ROOT/*.whl && \
    rm $CTRANSLATE2_ROOT/*.whl

# Install auto-gptq
ARG DEFAULT_CUDA_ARCH_LIST
ENV TORCH_CUDA_ARCH_LIST=${DEFAULT_CUDA_ARCH_LIST}

# 0.7.1 is missing Manifest.in so we build from repo version with it.
#RUN --mount=type=cache,target=/root/.cache PYPI_RELEASE=true pip install auto-gptq --no-build-isolation

RUN --mount=type=cache,target=/root/.cache git clone --branch add-manifest \
       https://github.com/AutoGPTQ/AutoGPTQ && \
    cd AutoGPTQ && python3 setup.py bdist_wheel && \
    pip install --no-cache-dir dist/*.whl && \
    cd .. && rm -rf AutoGPTQ

COPY . .

CMD ./entrypoint.sh
EXPOSE 19000
EXPOSE 19001
